### ISSUE TITLE
Exception is 'eaten'

### ISSUE THREAD

**Issue by tvdijen** [Tiqr/tiqr-server-libphp#19]
https://github.com/SURFnet/tiqr-server-libphp/blob/17c2da17f6e9d9d4f46c7a1116a233035ff51a5f/library/tiqr/Tiqr/UserSecretStorage.php#L59-L63

These exceptions never end up in any logging.. 
I had falsely set usersecretstorage to `memcache` and I found myself in a pickle to debug this.
Was discussed elsewhere with @pmeulen .

**Comment by pmeulen** [comment]
Fixed by https://github.com/SURFnet/tiqr-server-libphp/pull/30
