### ISSUE TITLE
Zendframework1 is deprecated

### ISSUE THREAD

**Issue by joostd** [Tiqr/tiqr-server-libphp#7]
Zendframework1  is used for sending push notifications. However, ZF1 is EOL and should be replaced by something new.

See https://framework.zend.com/blog/2016-06-28-zf1-eol.html

**Comment by tvdijen** [comment]
Don't need the complete framework for this:
https://github.com/zendframework/ZendService_Google_Gcm

**Comment by pmeulen** [comment]
APNS is now the only functionallity that uses the Zend library. Using https://github.com/zendframework/ZendService_Apple_Apns should be a drop in replacement. Otherwise using another library would work. 

I expect the autoloader would need work in any case.

**Comment by pmeulen** [comment]
Fixed in #49
